In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
submission = pd.read_csv('sample_submission.csv')

train.shape, test.shape, submission.shape

((230130, 6), (98550, 5), (98550, 2))

In [3]:
train.sample(5)

,id,date,country,store,product,num_sold
208898,208898,2016-05-10,Canada,Stickers for Less,Kerneler,471.0
27057,27057,2010-10-28,Kenya,Premium Sticker Mart,Kaggle Tiers,26.0
181691,181691,2015-07-12,Norway,Premium Sticker Mart,Kaggle,3391.0
168037,168037,2015-02-11,Canada,Stickers for Less,Kaggle Tiers,1024.0
207896,207896,2016-04-28,Singapore,Premium Sticker Mart,Kaggle,1915.0

In [4]:
test.sample(5)

           id        date  country                 store             product
39886  270016  2018-03-20  Finland     Discount Stickers              Kaggle
36630  266760  2018-02-12   Canada     Discount Stickers   Holographic Goose
42130  272260  2018-04-14   Canada  Premium Sticker Mart   Holographic Goose
93284  323414  2019-11-03    Italy  Premium Sticker Mart  Kerneler Dark Mode
37262  267392  2018-02-19   Canada     Discount Stickers        Kaggle Tiers

In [5]:
def get_dataframe_statistics(df):
    """
    This function computes and prints the number of unique values and 
    the percentage of unique values for each column in the provided DataFrame.

    Parameters:
    df (pandas.DataFrame): The DataFrame for which the statistics are computed.
    """
    for column in df.columns:
        unique_values_count = df[column].nunique()  # Number of unique values in the column
        percentage_unique = ((len(df) - unique_values_count) / len(df)) * 100  # Percentage of unique values
        unique_values = df[column].sort_values().unique()
        
        print(f'The number of unique values in {column} is {unique_values_count}')
        print(f'The percentage of unique values in {column} is {percentage_unique:.2f}%')
        print(f'The unique values are {unique_values}')
        print('\n')

In [6]:
get_dataframe_statistics(train)

The number of unique values in id is 230130
The percentage of unique values in id is 0.00%
The unique values are [     0      1      2 ... 230127 230128 230129]


The number of unique values in date is 2557
The percentage of unique values in date is 98.89%
The unique values are ['2010-01-01' '2010-01-02' '2010-01-03' ... '2016-12-29' '2016-12-30'
 '2016-12-31']


The number of unique values in country is 6
The percentage of unique values in country is 100.00%
The unique values are ['Canada' 'Finland' 'Italy' 'Kenya' 'Norway' 'Singapore']


The number of unique values in store is 3
The percentage of unique values in store is 100.00%
The unique values are ['Discount Stickers' 'Premium Sticker Mart' 'Stickers for Less']


The number of unique values in product is 5
The percentage of unique values in product is 100.00%
The unique values are ['Holographic Goose' 'Kaggle' 'Kaggle Tiers' 'Kerneler'
 'Kerneler Dark Mode']


The number of unique values in num_sold is 4037
The percentage of unique values in num_sold is 98.25%
The unique values are [5.000e+00 6.000e+00 7.000e+00 ... 5.643e+03 5.939e+03       nan]

In [7]:
get_dataframe_statistics(test)

The number of unique values in id is 98550
The percentage of unique values in id is 0.00%
The unique values are [230130 230131 230132 ... 328677 328678 328679]


The number of unique values in date is 1095
The percentage of unique values in date is 98.89%
The unique values are ['2017-01-01' '2017-01-02' '2017-01-03' ... '2019-12-29' '2019-12-30'
 '2019-12-31']


The number of unique values in country is 6
The percentage of unique values in country is 99.99%
The unique values are ['Canada' 'Finland' 'Italy' 'Kenya' 'Norway' 'Singapore']


The number of unique values in store is 3
The percentage of unique values in store is 100.00%
The unique values are ['Discount Stickers' 'Premium Sticker Mart' 'Stickers for Less']


The number of unique values in product is 5
The percentage of unique values in product is 99.99%
The unique values are ['Holographic Goose' 'Kaggle' 'Kaggle Tiers' 'Kerneler'
 'Kerneler Dark Mode']

- As suspected the ID column is obviously not one that can be used for prediction as it is entirely unique
- The training data is from 2010 to 2016 while the test data is from 2017 to 2019
- All the countries are the same in train and test
- The 3 store types are the same in the train and test
- The 5 product types are the same in the train and test

In [9]:
train[train['num_sold'].isna()][:50]

,id,date,country,store,product,num_sold
0,0,2010-01-01,Canada,Discount Stickers,Holographic Goose,NaN
45,45,2010-01-01,Kenya,Discount Stickers,Holographic Goose,NaN
90,90,2010-01-02,Canada,Discount Stickers,Holographic Goose,NaN
135,135,2010-01-02,Kenya,Discount Stickers,Holographic Goose,NaN
180,180,2010-01-03,Canada,Discount Stickers,Holographic Goose,NaN
225,225,2010-01-03,Kenya,Discount Stickers,Holographic Goose,NaN
270,270,2010-01-04,Canada,Discount Stickers,Holographic Goose,NaN
315,315,2010-01-04,Kenya,Discount Stickers,Holographic Goose,NaN
320,320,2010-01-04,Kenya,Stickers for Less,Holographic Goose,NaN
360,360,2010-01-05,Canada,Discount Stickers,Holographic Goose,NaN
405,405,2010-01-05,Kenya,Discount Stickers,Holographic Goose,NaN
410,410,2010-01-05,Kenya,Stickers for Less,Holographic Goose,NaN
450,450,2010-01-06,Canada,Discount Stickers,Holographic Goose,NaN
495,495,2010-01-06,Kenya,Discount Stickers,Holographic Goose,NaN
500,500,2010-01-06,Kenya,Stickers for Less,Holographic Goose,NaN
505,505,2010-01-06,Kenya,Premium Sticker Mart,Holographic Goose,NaN
540,540,2010-01-07,Canada,Discount Stickers,Holographic Goose,NaN
545,545,2010-01-07,Canada,Stickers for Less,Holographic Goose,NaN
585,585,2010-01-07,Kenya,Discount Stickers,Holographic Goose,NaN
590,590,2010-01-07,Kenya,Stickers for Less,Holographic Goose,NaN
595,595,2010-01-07,Kenya,Premium Sticker Mart,Holographic Goose,NaN
630,630,2010-01-08,Canada,Discount Stickers,Holographic Goose,NaN
675,675,2010-01-08,Kenya,Discount Stickers,Holographic Goose,NaN
680,680,2010-01-08,Kenya,Stickers for Less,Holographic Goose,NaN
720,720,2010-01-09,Canada,Discount Stickers,Holographic Goose,NaN
765,765,2010-01-09,Kenya,Discount Stickers,Holographic Goose,NaN
770,770,2010-01-09,Kenya,Stickers for Less,Holographic Goose,NaN
810,810,2010-01-10,Canada,Discount Stickers,Holographic Goose,NaN
855,855,2010-01-10,Kenya,Discount Stickers,Holographic Goose,NaN
900,900,2010-01-11,Canada,Discount Stickers,Holographic Goose,NaN
905,905,2010-01-11,Canada,Stickers for Less,Holographic Goose,NaN
945,945,2010-01-11,Kenya,Discount Stickers,Holographic Goose,NaN
950,950,2010-01-11,Kenya,Stickers for Less,Holographic Goose,NaN
955,955,2010-01-11,Kenya,Premium Sticker Mart,Holographic Goose,NaN
990,990,2010-01-12,Canada,Discount Stickers,Holographic Goose,NaN
1035,1035,2010-01-12,Kenya,Discount Stickers,Holographic Goose,NaN
1040,1040,2010-01-12,Kenya,Stickers for Less,Holographic Goose,NaN
1045,1045,2010-01-12,Kenya,Premium Sticker Mart,Holographic Goose,NaN
1080,1080,2010-01-13,Canada,Discount Stickers,Holographic Goose,NaN
1125,1125,2010-01-13,Kenya,Discount Stickers,Holographic Goose,NaN
1128,1128,2010-01-13,Kenya,Discount Stickers,Kerneler,NaN
1130,1130,2010-01-13,Kenya,Stickers for Less,Holographic Goose,NaN
1135,1135,2010-01-13,Kenya,Premium Sticker Mart,Holographic Goose,NaN
1170,1170,2010-01-14,Canada,Discount Stickers,Holographic Goose,NaN
1175,1175,2010-01-14,Canada,Stickers for Less,Holographic Goose,NaN
1215,1215,2010-01-14,Kenya,Discount Stickers,Holographic Goose,NaN
1220,1220,2010-01-14,Kenya,Stickers for Less,Holographic Goose,NaN
1225,1225,2010-01-14,Kenya,Premium Sticker Mart,Holographic Goose,NaN
1260,1260,2010-01-15,Canada,Discount Stickers,Holographic Goose,NaN
1305,1305,2010-01-15,Kenya,Discount Stickers,Holographic Goose,NaN

In [ ]:
# Get the statistics for the rows where the num_sold is NaN
get_dataframe_statistics(train[train['num_sold'].isna()])

In [ ]:
train.info()

In [10]:
# Convert the date column to datetime
train['date'] = pd.to_datetime(train['date'])

In [11]:
# Fill rows with NaN in 'num_sold'
train = train.fillna(0)

In [ ]:
# Group by date and country to calculate total sales
sales_trends_country = train.groupby(['date', 'country'])['num_sold'].sum().reset_index()

# Plot sales trends
plt.figure(figsize=(12, 6))

sales_trends_country['date'] = pd.to_datetime(sales_trends_country['date'])

for country in sales_trends_country['country'].unique():
    country_data = sales_trends_country[sales_trends_country['country'] == country]
    # plt.plot(country_data['date'], country_data['num_sold'], label=country)
    # Flatten the data to ensure no multi-dimensional arrays are passed
    dates = country_data['date'].values
    num_sold = country_data['num_sold'].values
    
    # Plot the data for the current country
    plt.plot(dates, num_sold, label=country)

plt.title('Monthly Sales Trends by Country', fontsize=16)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Total Sales', fontsize=12)
plt.legend(title='Country')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

In [ ]:
# Group by date and store to calculate total sales
sales_trends_store = train.groupby(['date', 'store'])['num_sold'].sum().reset_index()

# Plot sales trends
plt.figure(figsize=(12, 6))

sales_trends_store['date'] = pd.to_datetime(sales_trends_store['date'])

for store in sales_trends_store['store'].unique():
    store_data = sales_trends_store[sales_trends_store['store'] == store]
    # plt.plot(store_data['date'], store_data['num_sold'], label=store)
    # Flatten the data to ensure no multi-dimensional arrays are passed
    dates = store_data['date'].values
    num_sold = store_data['num_sold'].values
    
    # Plot the data for the current store
    plt.plot(dates, num_sold, label=store)

plt.title('Monthly Sales Trends by Store', fontsize=16)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Total Sales', fontsize=12)
plt.legend(title='Store')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

In [ ]:
# Group by product and country to calculate total sales
sales_trends_country = train.groupby(['product', 'country'])['num_sold'].sum().reset_index()

# Plot sales trends
plt.figure(figsize=(12, 6))

for country in sales_trends_country['country'].unique():
    country_data = sales_trends_country[sales_trends_country['country'] == country]
    # Flatten the data to ensure no multi-dimensional arrays are passed
    products = country_data['product'].values
    num_sold = country_data['num_sold'].values
    
    # Plot the data for the current country
    plt.plot(products, num_sold, label=country)

plt.title('Monthly Sales Trends by Country', fontsize=16)
plt.xlabel('product', fontsize=12)
plt.ylabel('Total Sales', fontsize=12)
plt.legend(title='Country')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

In [ ]:
# Group data by product and country to sum up sales
product_sales = train.groupby(['product', 'country'])['num_sold'].sum().unstack(fill_value=0)

# Create a heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(product_sales, annot=True, fmt='.0f', cmap='coolwarm', cbar=True)

# Add titles and labels
plt.title('Product Popularity Across Countries', fontsize=16)
plt.xlabel('Country', fontsize=12)
plt.ylabel('Product', fontsize=12)

plt.tight_layout()
plt.show()

In [ ]:
# Convert the 'date' column to datetime format if not already done
train['date'] = pd.to_datetime(train['date'])

# Extract the year and month for grouping
train['month'] = train['date'].dt.to_period('M')

# Group data by month and country, summing up sales
monthly_sales = train.groupby(['month', 'country'])['num_sold'].sum().reset_index()

# Convert 'month' back to datetime for plotting
monthly_sales['month'] = monthly_sales['month'].dt.to_timestamp()

# Plot sales trends
plt.figure(figsize=(12, 6))
for country in monthly_sales['country'].unique():
    country_data = monthly_sales[monthly_sales['country'] == country]
    # Flatten the data to ensure no multi-dimensional arrays are passed
    month = country_data['month'].values
    num_sold = country_data['num_sold'].values
    
    # Plot the data for the current country
    plt.plot(month, num_sold, label=country)

# Add titles and labels
plt.title('Monthly Sales Trends by Country', fontsize=16)
plt.xlabel('Month', fontsize=12)
plt.ylabel('Total Sales', fontsize=12)
plt.legend(title='Country')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

In [ ]:
# Group by store and product to sum sales
store_product_sales = train.groupby(['store', 'product'])['num_sold'].sum().unstack(fill_value=0)

# Plot stacked bar chart
store_product_sales.plot(kind='bar', stacked=True, figsize=(12, 6))

plt.title('Product Popularity by Store', fontsize=16)
plt.xlabel('Store', fontsize=12)
plt.ylabel('Total Sales', fontsize=12)
plt.legend(title='Product', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

In [ ]:
# Group by product to sum sales
product_sales = train.groupby('product')['num_sold'].sum()

# Plot pie chart
plt.figure(figsize=(8, 8))
product_sales.plot(kind='pie', autopct='%1.1f%%', startangle=140, cmap='tab10')

plt.title('Top Selling Products Overall', fontsize=16)
plt.ylabel('')  # Remove default ylabel
plt.tight_layout()
plt.show()

In [ ]:
# Group by country and product, find max sold product in each country
country_popular_product = train.groupby(['country', 'product'])['num_sold'].sum().reset_index()
most_popular = country_popular_product.loc[country_popular_product.groupby('country')['num_sold'].idxmax()]

# Plot bar chart
plt.figure(figsize=(8, 6))
plt.bar(most_popular['country'], most_popular['num_sold'], color='skyblue')
for i, row in most_popular.iterrows():
    plt.text(row['country'], row['num_sold'], row['product'], ha='center', fontsize=10)

plt.title('Country-wise Most Popular Product', fontsize=16)
plt.xlabel('Country', fontsize=12)
plt.ylabel('Sales of Most Popular Product', fontsize=12)
plt.tight_layout()
plt.show()

In [ ]:
# Group by country and product, find min sold product in each country
country_popular_product = train.groupby(['country', 'product'])['num_sold'].sum().reset_index()
most_popular = country_popular_product.loc[country_popular_product.groupby('country')['num_sold'].idxmin()]

# Plot bar chart
plt.figure(figsize=(8, 6))
plt.bar(most_popular['country'], most_popular['num_sold'], color='green')
for i, row in most_popular.iterrows():
    plt.text(row['country'], row['num_sold'], row['product'], ha='center', fontsize=10)

plt.title('Country-wise Most Popular Product', fontsize=16)
plt.xlabel('Country', fontsize=12)
plt.ylabel('Sales of Most Popular Product', fontsize=12)
plt.tight_layout()
plt.show()

In [ ]:
# Create a boxplot for sales distribution
plt.figure(figsize=(12, 6))
sns.boxplot(data=train, x='store', y='num_sold', hue='product')

plt.title('Product Sales Distribution by Store', fontsize=16)
plt.xlabel('Store', fontsize=12)
plt.ylabel('Sales', fontsize=12)
plt.legend(title='Product', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

In [ ]:
# Filter data for Kaggle-related products
# kaggle_products = train[train['product'].str.contains('Kaggle')]
kaggle_products = train.copy()

# Group by product and country to sum sales
kaggle_sales = kaggle_products.groupby(['country', 'product'])['num_sold'].sum().unstack(fill_value=0)

# Plot grouped bar chart
kaggle_sales.plot(kind='bar', figsize=(12, 6))

plt.title('Kaggle Product Sales Comparison', fontsize=16)
plt.xlabel('Country', fontsize=12)
plt.ylabel('Total Sales', fontsize=12)
plt.legend(title='Product', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

In [ ]:
# Filter data for Kaggle-related products
# kaggle_products = train[train['product'].str.contains('Kaggle')]
kaggle_products = train.copy()

# Group by product and store to sum sales
kaggle_sales = kaggle_products.groupby(['store', 'product'])['num_sold'].sum().unstack(fill_value=0)

# Plot grouped bar chart
kaggle_sales.plot(kind='bar', figsize=(12, 6))

plt.title('Kaggle Product Sales Comparison', fontsize=16)
plt.xlabel('Store', fontsize=12)
plt.ylabel('Total Sales', fontsize=12)
plt.legend(title='Product', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

In [ ]:
# Pivot table to create a matrix of products vs. store sales
product_sales_matrix = train.pivot_table(values='num_sold', index='product', columns='store', aggfunc='sum', fill_value=0)

# Plot cluster map
sns.clustermap(product_sales_matrix, cmap='viridis', metric='euclidean', method='ward', figsize=(10, 8), annot=False)

plt.title('Sales Similarities Between Products')
plt.show()

In [ ]:
# Convert 'date' column to datetime if not already done
train['date'] = pd.to_datetime(train['date'])

# Extract quarterly period
train['quarter'] = train['date'].dt.to_period('Q')

# Group by quarter and calculate total sales
quarterly_sales = train.groupby(['quarter', 'country'])['num_sold'].sum().reset_index()
quarterly_sales['quarter'] = quarterly_sales['quarter'].dt.to_timestamp()

# Plot line chart for seasonal trends
plt.figure(figsize=(12, 6))
for country in quarterly_sales['country'].unique():
    country_data = quarterly_sales[quarterly_sales['country'] == country]
    # Flatten the data to ensure no multi-dimensional arrays are passed
    quarter = country_data['quarter'].values
    num_sold = country_data['num_sold'].values
    plt.plot(quarter, num_sold, label=country)

plt.title('Seasonal Trends in Sales (Quarterly)', fontsize=16)
plt.xlabel('Quarter', fontsize=12)
plt.ylabel('Total Sales', fontsize=12)
plt.legend(title='Country')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

In [ ]:
# Group data by date and product to find total sales
daily_sales = train.groupby(['date', 'product'])['num_sold'].sum().reset_index()

# Plot scatter plot
plt.figure(figsize=(12, 6))
plt.scatter(daily_sales['date'], daily_sales['num_sold'], alpha=0.6, c='red', edgecolor='k')

plt.title('Sales Anomalies Over Time', fontsize=16)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Total Sales', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

In [ ]:
daily_sales.sort_values(by='num_sold', ascending=False)

In [ ]:
# Sort the data by 'num_sold' in descending order
sorted_data = train.sort_values(by='num_sold', ascending=False)

In [ ]:
sorted_data[:10]

## Visualization Notes

- There is always a spike in sales at the beginning of the year (so week of the year, date-month combo is important)
- Kaggle is always the highest selling product in every country, followed by Kaggle Tiers
- Finland and Canada trends are very similar
- The product sales trend and percentages are the same regardless of the country

## Feature Ideas from EDA

#### COUNTRY, COUNTRY-STORE, COUNTRY-STORE-PRODUCT, COUNTRY-PRODUCT VALUES
- Yesterday average (Use mean if there no value)
- Last week average (Use mean if there no value)
- Last month average (Use mean if there no value)
- Last 3 days average

#### Holiday Features
- is_weekend
- is_holiday (America, Norway, Kenya, Canada, Finland, Italy, Singaport)
- holiday_yesterday (America)
- holiday_2days_ago (America)
- holiday_tomorrow (America)
- holiday_in_2days (America)

#### Period features
- quarter
- month
- day
- date


#### CAT FEATURES
- target encode
- one hot encode


#### Drop Features
- id

#### POST PROCESSING
- rounding